---
- name: Deploy Site-B
  hosts: siteb
  become: yes

  tasks:
    - name: install docker prereqs
      pip:
        name: docker

    - name: launch the apache-simple container on the site-b nodes
      docker_container:
        name: apache-simple
        image: quay.io/pchen2145/ansible-for-devops-siteb
        ports:
          - "8080:8080"
